#!/usr/bin/env bash
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd)"
################## Color ##########################

# Reset
Color_Off='[0m'  # Text Reset
Bold='[1m'       # Bold

NVIDIA_SMI_PREFIX=${NVIDIA_SMI_PREFIX:-}

##################################################

case "$OSTYPE" in
    solaris*) platform="SOLARIS" ;;
    darwin*)  platform="OSX" ;;
    linux*)   platform="LINUX" ;;
    bsd*)     platform="BSD" ;;
    msys*)    platform="WINDOWS" ;;
    *)        platform="unknown: $OSTYPE" ;;
esac

if [[ $platform != LINUX ]]; then
    echo "This script dose not support $platform." >&2
    exit 1
fi

if [ ${#@} == 0 ]; then
  args="-c"
else
  args="$@"
fi


if command -v "${NVIDIA_SMI_PREFIX}nvidia-smi" >/dev/null; then
  coproc gpudetailfd { ${DIR}/gpustat --no-header $@ | sed 's/^/        /'; }
  exec 3>&${gpudetailfd[0]}
fi

hostname="$(hostname)"
now="$(date)"
echo "${Bold}${hostname}${Color_Off}   ${now}"
echo -en "   CPU: " && ${DIR}/cpu-usage | ${DIR}/ascii-bar 40
echo
echo -en "   MEM: " && ${DIR}/mem-usage | ${DIR}/ascii-bar 40
if command -v "${NVIDIA_SMI_PREFIX}nvidia-smi" >/dev/null; then
  echo
  echo -en "   GPU: " && ${DIR}/gpu-usage | ${DIR}/ascii-bar 40
  echo
  echo "$(cat <&3)"
fi
